Fix clippy warnings and some errors on Windows (#382)
This PR clippy warnings found at:

https://github.com/killercup/cargo-edit/runs/417584635?check_suite_focus=true

and several Windows errors found at:

https://github.com/killercup/cargo-edit/runs/417584722?check_suite_focus=true

I confirmed all warnings and errors except for one were fixed on my fork repository:

https://github.com/rhysd/cargo-edit/actions/runs/35804962

1 error is remaining on Windows node. But I could not find the reason since it was not reproducible on my local Windows machine. This PR does not fix it.

```
failures:

---- invalid_manifest stdout ----
thread 'invalid_manifest' panicked at 'Assertion failed for `D:\a\cargo-edit\cargo-edit\target\debug\cargo-upgrade upgrade --manifest-path C:\Users\RUNNER~1\AppData\Local\Temp\.tmpl9pxgX\Cargo.toml`
with: Unexpected stderr

with: Didn't match.
diff=
`` Command failed due to unhandled error: Unable to parse Cargo.toml

Caused by: Manifest not valid TOML
Caused by: TOML parse error at line 1, column 6
  |
-1 | This is clearly not a valid Cargo.toml.
+1 | This is clearly not a valid Cargo.toml.
 
   |      ^
Unexpected `i`
Expected `=`
```', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\assert_cli-0.6.3\src\assert.rs:441:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```